### ISSUE TITLE
Please display all labels in "Landmarks on page" menu

### ISSUE THREAD

**Issue by carmacleod** [matatk/landmarks#82] opened 2017-08-15 18:10 UTC
Some of our pages have multiple navigation landmarks, and these are labelled using aria-label or aria-labelledby. It would be great if those labels would show up in the Landmarks menu as "Label (navigation)". Currently, only the labelled regions include the label, as "Label (region)". See screen snap, below.

![image](https://user-images.githubusercontent.com/3331913/29329161-edc4002a-81c2-11e7-81a9-f52154bcaec7.png)

**Comment by matatk** [comment] 2017-08-17 09:48
Thanks for reporting this. It's certainly intended that labelling is picked up on *any* landmark, not just generic `region` landmarks, and there are tests that cover this for a number of region types (though not specifically navigation).

Multiple `navigation` landmarks that are labelled are picked up here: http://www.bbc.co.uk/news

Please could you either send a URL to your page (assuming it's publicly-reachable) or code snippets for those two navigation regions (the landmark element/container should be all that's needed)?

**Comment by carmacleod** [comment] 2017-08-17 12:39
Oh, wow - I checked another page (same landmarks) and the labels do show up.
![image](https://user-images.githubusercontent.com/3331913/29412278-0b2e7712-8326-11e7-8756-f0987c851b6d.png)

And then I checked yet another page with similar landmarks, and one nav label shows up, but the other doesn't.
![image](https://user-images.githubusercontent.com/3331913/29412375-68011fa8-8326-11e7-9dbd-a49658ab3081.png)

In each case, the code for that first nav is identical:
<nav id="sideMenu" class="sideMenu" aria-label="Sidebar"></nav>

I'll see if I can find any difference between those pages. Maybe one landmark is hardcoded in html and another is being added in javascript - I'll check that first.

The app is public (you would need to create an account) but I haven't released some of the landmark code yet - it needs more testing first. (I'm adding landmarks to a whole bunch of pages, and I love your landmark extension - thanks for working on it!)

**Comment by matatk** [comment] 2017-08-17 13:02
Ah, looks like this may relate to #80 then.  The reason that sometimes some/all show up *could* be because there is a short pause after the page has loaded before a search for landmarks is carried out, but that pause will vary slightly in length.

I am hoping to be able to do some proper exploration of #80 early next month.

Glad you are finding the extension helpful :-).  Thanks for your detailed feedback.

**Comment by carmacleod** [comment] 2017-08-23 17:16
Would it be possible to recalculate the list of landmarks at the point where the user drops down the menu? The labels are sure to be correct at that point.  :)

**Comment by matatk** [comment] 2017-08-31 09:27
The short answer is yes (looks like that'd help with #80 too).

The longer answer is: I wonder how this should affect (or not) the feature that displays the number of landmarks found on the page very early on as a badge.

It appears that we are heading towards me adding an issue as a tracker for a feature whereby they're re-calculated each time they are requested, but I'm still mindful that that's not so elegant compared to where we are now, and I am wondering if there's any way I can (efficiently) work around that.  Haven't been able to look into it properly yet, but should be able to within the next week.

**Comment by matatk** [comment] 2017-09-07 21:57
Hi @carmacleod... I'm experimenting with a proper solution for dynamic content. It may come soon, but it may take a while, as there's a lot to test. Meanwhile I am considering releasing 2.0.8 as that contains some helpful fixes and improvements.

I was wondering if you are able to determine how long your scripts, specifically regarding this issue, usually take to run, after the page has loaded?

(I have already (in my development version) increased the time that Landmarks waits after the page has loaded in order to scan for landmarks, and thought that, in the meantime, this might provide a workaround for this issue, which I expect will be affecting other sites that work in a similar manner.)

**Comment by carmacleod** [comment] 2017-09-08 13:57
They can take 5 - 10 seconds sometimes to load the page, possible plugins, and resources.
(probably not what you want to hear ;)

Looking forward to 2.0.8. I have been running this on Chrome - should I try the extension in Firefox instead?

**Comment by matatk** [comment] 2017-09-08 15:07
Thanks for getting back to me so quickly. That's probably longer than it should pause on *all* pages before trying to find landmarks; I had increased the initial gap to two seconds (from one), and it doesn't seem too bad, but if that still isn't nearly enough, I may go back to plan A.

I may still push the dynamic stuff (and therefore the full solution to this issue) to the next release; still experimenting with it. Important to ensure it's robust, and there are some good improvements ready to go.

From your perspective, Landmarks should behave identically on Firefox and Chrome.

**Comment by matatk** [comment] 2017-09-19 13:24
I've released stable version 2.0.8, which should be available in Chrome now and Firefox shortly. It contains the fixes we already discussed, but doesn't address this issue.

Turns out I am also able to easily set up a 'development channel' in Firefox, so I have also released an experimental version "2.1.0alpha1" that you could try to see if it helps with this issue.  Important things to note about this release:

* Experimental releases are not fully reviewed by Mozilla (they pass automated checks, but get no human review).
* The keyboard shortcuts do not work correctly; if it refreshes the landmarks on the page, your position is lost.
* The performance has not been remotely tuned, so may well be quite slow.

If you have time, I'd be interested as to whether this fixes the problems you were having though (it should also address navigation regions that appear and disappear).  You can get it by scrolling down to "Development Channel" and installing from there on the [Mozilla Add-ons page](https://addons.mozilla.org/en-GB/firefox/addon/landmarks/).

**Comment by carmacleod** [comment] 2017-09-19 20:20
Thank-you so much for 2.1.0alpha1! It works really well. I'm doing my testing in FF now.  :)
I was worried, though, because 2.0.8 is actually quite broken for me. I tested it in Chrome yesterday, and I only got 2 unlabelled landmark regions showing up on a page that actually has 5 labelled landmarks plus a main.

**Comment by matatk** [comment] 2017-09-19 20:46
> Thank-you so much for 2.1.0alpha1! It works really well. I'm doing my testing in FF now. :)

Glad to hear it, and thanks for the quick feedback. Once you've had some time to try it out, please let me know if there are any problems.  If it works, I'll close this issue, but continue trying to improve the efficiency of the MutationObserver technique, and will track that in #84.

> I was worried, though, because 2.0.8 is actually quite broken for me. I tested it in Chrome yesterday, and I only got 2 unlabelled landmark regions showing up on a page that actually has 5 labelled landmarks plus a main.

Do those pages work in the same way as you described above, with localised content being loaded in after the page has loaded?  I actually reduced the timeout in 2.0.8 (because I thought that, seeing as two seconds was insufficient, I may as well make it wait *less* long before trying to find landmarks, because I was hoping that MutationObservers (in what will be 2.1.0) would address the underlying problem.

For pages where the labels are in the HTML when the page loads, I have not seen any regressions, but if you happen to, please let me know.

**Comment by carmacleod** [comment] 2017-10-03 19:07
The MutationObservers in 2.1.0alpha1 are working well. It is cool to see the landmark count increment as landmarks are added/removed in JS.  I also like the [...] before there's any count ready.  :)
I haven't noticed any performance problems. Let me know when it's in Chrome!  :)

**Comment by matatk** [comment] 2017-10-11 13:48
Great. I will close this now and move on to the more general #84.

**Closed by matatk** 2017-10-11 13:48 UTC
